version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin-api
    container_name: admin-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    volumes:
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
